### ISSUE TITLE
Validation of text input fields before adding to the expense list 

### ISSUE THREAD

**Issue by taha2218** [pccoeacm/expenses-flutter-app#3]
**Bug**
Empty text fields are being accepted and added to the existing expense list.

**Expected behaviour**
Text fields need to be validated before they are added to the Expense List. An alert box should pop up showing "Empty Fields not allowed!" if the fields are invalid.

**Screen Shots**
![image](https://user-images.githubusercontent.com/45139576/94961968-5136de80-0513-11eb-8131-bd363674074d.png)
![image](https://user-images.githubusercontent.com/45139576/94962371-f81b7a80-0513-11eb-830a-a661c8d32c81.png)

**Comment by NachiketaVadera** [comment]
@tejasmorkar @taha2218 Could you please assign me to the issue. I would love to work on it. Thank you.

**Comment by tejasmorkar** [comment]
Sure, go ahead!

**Comment by NachiketaVadera** [comment]
@tejasmorkar Thank you. Submitted a PR #7 for the same.
