### ISSUE TITLE
Use tags for categorization of expense items

### ISSUE THREAD

**Issue by taha2218** [pccoeacm/expenses-flutter-app#6]
**Features**
Assign tag fields to expense items so that they can be used to categorize efficiently.
Provide the option in the menu for viewing of all the available tags to choose from.

**Where to edit**
Navigate to "expenses-flutter-app/lib/widgets/expense.dart" for expense widget
Navigate to "expenses-flutter-app/lib/pages/home.dart" for including required options to menu widget

**Comment by diegoalvis** [comment]
I'd like work on this. Feel free to assign me this issue 🙂

**Comment by tejasmorkar** [comment]
Okay sure @diegoalvis
